//! App-wide theme state, driven by [`crate::theme`] blocks.

use std::sync::atomic::{AtomicUsize, Ordering};

/// The OS-level light/dark preference, used to pick a starting theme
/// variant before the app's first page renders.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum ThemeMode {
    Light,
    Dark,
}

static THEME_INDEX: AtomicUsize = AtomicUsize::new(0);

/// Returns the currently active [`crate::theme`] variant, by declaration
/// order.
pub fn theme_index() -> usize {
    THEME_INDEX.load(Ordering::Relaxed)
}

/// Sets the starting theme variant from the OS's light/dark preference.
pub fn init_theme_mode(mode: ThemeMode) {
    THEME_INDEX.store(
        if mode == ThemeMode::Dark { 1 } else { 0 },
        Ordering::Relaxed,
    );
}

/// Switches to the [`crate::theme`] variant at `index` (by declaration
/// order) and redisplays the current page with the new colors. An
/// out-of-range `index` clamps to the last declared variant.
///
/// ```ignore
/// goyda::set_theme(Dark);
/// ```
pub fn set_theme(index: usize) {
    THEME_INDEX.store(index, Ordering::Relaxed);
    crate::platform::rerender();
}

/// Switches to the next of `count` theme variants, wrapping back to the
/// first after the last. Prefer the `next_theme()` function generated by
/// [`crate::theme`] over calling this directly.
pub fn cycle_theme(count: usize) {
    if count == 0 {
        return;
    }
    set_theme((theme_index() + 1) % count);
}
