[package]
name = "goyda-derive"
version = "0.1.1"
edition = "2024"
description = "#[page]/#[component] proc macros for goyda - internal, not meant to be used directly"
license = "MIT"

[lints]
workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full", "extra-traits", "visit", "visit-mut"] }
quote = "1.0"
proc-macro2 = "1.0"
jni = { version = "0.21.1", features = ["invocation"] }
petgraph = "0.8.3"
